name: Artifact Image Push Trigger

# .github/workflows/<any-name>.yml
on:
  workflow_dispatch:
    inputs:
      reason:
        description: Why it was triggered
        required: false

jobs:
  handle-image-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run image push related jobs
        run: |
          echo "Triggered by image push event"
          # Add your deployment or build steps here
